{% set version = "2.2.1" %}

package:
  name: pykakasi
  version: {{ version }}

source:
  url: https://github.com/miurahr/pykakasi/archive/v{{ version }}.tar.gz
  sha256: 65c813cc4e61c65933dd41c70329289360434d30982e41f6ad418dd8033240dd

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - wheel
    - deprecated
    - jaconv
  run:
    - python
    - deprecated
    - jaconv
    # unfortunately, this really run-depends on setuptools, see
    # https://github.com/miurahr/pykakasi/blob/v2.1.0/src/pykakasi/properties.py#L8
    - setuptools

test:
  # will run run_test.py
  requires:
    - pytest
    - pytest-benchmark
    - pytest-profiling
    - py-cpuinfo
  imports:
    - pykakasi
  source_files:
    - tests/

about:
  home: https://github.com/miurahr/pykakasi
  license: GPL-3.0-only
  license_file: COPYING
  summary: Convert Japanese Kana-kanji sentences into Kana-Roman in simple algorithm.

  description: |
    `pykakasi` is a Python Natural Language Processing (NLP) library to transliterate _hiragana_,
    _katakana_ and _kanji_ (Japanese text) into _romaji_ (Latin/Roman alphabet). It can handle characters in NFC form.

    It is based on the kakasi library, which is written in C.

  doc_url: https://pykakasi.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/miurahr/pykakasi

extra:
  recipe-maintainers:
    - h-vetinari
